[build]
builder = "nixpacks"

[deploy]
startCommand = "python3 app.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
PORT = "8080"
PYTHON_VERSION = "3.11"
FLASK_ENV = "production"
PYTHONUNBUFFERED = "1"
TZ = "Asia/Shanghai"

[healthcheck]
path = "/api/status"
interval = 30
timeout = 10
retries = 3

[networking]
port = 8080